# Generated by Django 5.2 on 2025-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblio',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='biblio',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
