# Generated by Django 5.2 on 2025-04-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0003_biblio_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblio',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
