# Generated by Django 5.2 on 2025-04-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_biblio_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblio',
            name='image_url',
        ),
        migrations.AddField(
            model_name='biblio',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
